language: bash

install:
- echo $PWD
- git clone https://github.com/tern-tools/tern.git ~/tern
- git clone https://github.com/nexB/scancode-toolkit.git ~/scancode

      
script: 
      - bash test.sh
      - bash Scancode.sh
