language: bash

dist: bionic

python:
    - "3.6"

services:
    - docker
  
before_install:
    - sudo apt-get update

install:
    - cd Install_Scripts
    - bash Clone_Repositories.sh
    - bash Scancode_Install.sh
    - bash Tern_Install.sh
    - bash Fossology_Toolkit_-_Ninka_and_Nomos_Install.sh


jobs:
  include:
    - stage: test
      script: 
        - bash Test_Scripts/Test.sh
