language: bash

dist: bionic

python:
    - "3.6"

services:
    - docker
  
before_install:
    - sudo apt-get update

install:
    - pwd
    - sudo ./home/travis/build/enterprisecomputinglizenzermittlung/master_projekt20/Install_Scripts/Clone_Repositories.sh
    - sudo ./home/travis/build/enterprisecomputinglizenzermittlung/master_projekt20/Install_Scripts/Scancode_Install.sh
    - sudo ./home/travis/build/enterprisecomputinglizenzermittlung/master_projekt20/Install_Scripts/Tern_Install.sh
    - sudo ./home/travis/build/enterprisecomputinglizenzermittlung/master_projekt20/Install_Scripts/Fossology_Toolkit_-_Ninka_and_Nomos_Install.sh


jobs:
  include:
    - stage: test
      script: ./Install_Scripts/Tern_Install.sh
