language: bash

dist: bionic

python:
    - "3.6"

services:
    - docker
  
before_install:
    - sudo apt-get update

install:
    - pwd
    - ls
    - cd Install_Scripts
    - ls
    - sudo ./Clone_Repositories.sh
    - sudo ./Scancode_Install.sh
    - sudo ./Tern_Install.sh
    - sudo ./Fossology_Toolkit_-_Ninka_and_Nomos_Install.sh


jobs:
  include:
    - stage: test
      script: ./Install_Scripts/Tern_Install.sh
