language: bash

install:
- git clone https://github.com/tern-tools/tern.git ~/tern
- git clone https://github.com/nexB/scancode-toolkit.git ~/scancode
cd ..
echo $PWD
      
script: 
      - bash test.sh
      - bash TC_1.sh
