language: bash

dist: bionic

python:
  - "3.6"

services:
  - docker
  
deploy:
  provider: pypi
  username: ...
  password: ...
  distributions: "sdist bdist_wheel"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-venv

install:
- echo $PWD
- git clone https://github.com/tern-tools/tern.git ~/tern
#- git clone https://github.com/nexB/scancode-toolkit.git ~/scancode

      
script: 
      - bash test.sh
      #- bash Scancode.sh
      - bash Tern.sh
