language: bash

services:
  - docker

install:
- echo $PWD
- git clone https://github.com/tern-tools/tern.git ~/tern
- git clone https://github.com/nexB/scancode-toolkit.git ~/scancode
- pip install 

      
script: 
      - bash test.sh
      #- bash Scancode.sh
      - bash Tern.sh
