language: bash

dist: bionic

python:
    - "3.6"

services:
    - docker
  
before_install:
    - sudo apt-get update

install:
    - ./Install_Scripts/Clone_Repositories.sh
    - ./Install_Scripts/Scancode_Install.sh
    - ./Install_Scripts/Tern_Install.sh
    - ./Install_Scripts/Fossology_Toolkit_-_Ninka_and_Nomos_Install.sh


