language: bash

dist: bionic

python:
  - "3.6"

services:
  - docker
  
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-venv
  - sudo apt-get install python-setuptools

install:
- echo $PWD
- git clone https://github.com/tern-tools/tern.git ~/tern
#- git clone https://github.com/nexB/scancode-toolkit.git ~/scancode

jobs:
  include:
   # - stage: test
   #   script: 
   #     - bash test.sh
    - stage: Tern
      script:
   #     - bash Scancode.sh
        - bash Tern.sh
